[project]
name = "midas-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mpark108", email = "mpark108@illinois.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "paho-mqtt>=2.1.0",
    "pyserial>=3.5",
]

[project.scripts]
midas-base = "midas_base:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
